# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41a9e6222c60309b103cc5bc9a4447da790dfc30fbab41fb2537d988589b5a549dfded17bbe49cd5dcd191c8b725b62c6a6f291020e7c5c8491ba411cf94419f

test:
  secret_key_base: 24fe67aae9057b769c83a57d3371c93290f04293296a6d30e11b8b9c6eb00532c6a1e75a31dfecbf4259a7166d2ed4c69cb2430f26e535a024aa38ad7f9c9f4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
